name: api

on:
  push:
    branches: [ master ]
    paths:
    - 'api/**'
  pull_request:
    paths:
    - 'api/**'
  release:
    types: [ published ]

env:
  IMAGE_NAME: api

defaults:
  run:
    working-directory: ./api

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - uses: actions/checkout@v2
      with:
        projectBaseDir: api

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v2
      with:
        go-version: 1.12
    - uses: actions/checkout@v2
    - run: go mod download
    - run: go get -v -d ./...
    - run: go build -v -o app
    - run: go test -v .
  push:
    needs: build
    if: contains(github.ref, 'tags')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build_step.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      id: build_step
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        docker build -t vitaes/$IMAGE_NAME:latest .
        docker tag vitaes/$IMAGE_NAME:latest vitaes/$IMAGE_NAME:$VERSION
    - name: Login to Docker hub
      run: |
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | \
        docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
    - name: Push image
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        docker push vitaes/$IMAGE_NAME:latest
        docker push vitaes/$IMAGE_NAME:$VERSION
    - name: Logout from Docker hub
      run: docker logout
  deploy:
    needs: push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Setup kubeconfig
      run: doctl kubernetes cluster kubeconfig save vitaes
    - name: Rollout new container
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        kubectl set image deployment/$IMAGE_NAME \
          $IMAGE_NAME=vitaes/$IMAGE_NAME:$VERSION
  